### ISSUE TITLE
Create car class

### ISSUE THREAD

**Issue by lutca1320** [lutca1320/Intersection#2]
## Description
- `Car` can senses nearby object (ex. other cars)
- `Car` is independent with the other cars, so `Car` Go / Stop with inner function.

## TODO

- [x] Migrate Level Blueprint things to car class
- [x] Create collision prevention feature
- [x] Configure Go / Stop Motion
